* Challenge - Chapter 2 
  :PROPERTIES:
  :Created: <2023-05-01 Mon>
  :END:

1. Pick an open source implementation of a language you like. Download the source code and poke around in it. Try to find the code that implements the scanner and parser. Are they handwritten, or generated using tools like Lex and Yacc? (.l or .y files usually imply the latter.)

   - I Chose [[https://github.com/microsoft/TypeScript][Typescript]] for this challenge.
   - It uses its own handwritten scanner and compiler.

2. Just-in-time compilation tends to be the fastest way to implement dynamically typed languages, but not all of them use it. What reasons are there to not JIT?   
  
   Hmm, I am not fully sure if there's one particualr reason but using JIT adds uncessarry steps into the compiler process and introduces problems such as:

   1. High memory usage
   2. Increased memory time.
   3. less security etc.

 3. Most Lisp implementations that compile to C also contain an interpreter that lets them execute Lisp code on the fly as well. Why?

    An intepreter is provided in many lisp implementaions to make it more flexible to work with it.
